// AUTO-GENERATED. DO NOT EDIT.
// Generated by: scripts/generate-frontend-registry.cjs

export type RegistryChainKey = 'gate-testnet' | 'sepolia'

export type RegistryTokenKey = 'USDT'

export type TokenKind = 'OFT' | 'OFT_ADAPTER'

export interface ChainMeta {
  network: RegistryChainKey
  chainId: number
  eid: number
  name: string
  nativeCurrency: { name: string; symbol: string; decimals: number }
  rpcUrl: string
  explorerUrl: string
}

export interface TokenOnChain {
  token: string
  adapter: string
}

export interface TokenMeta {
  key: RegistryTokenKey
  symbol: string
  decimals: number
  kind: TokenKind
  perChain: Partial<Record<RegistryChainKey, TokenOnChain>>
}

export const REGISTRY = {
  chains: {
  "gate-testnet": {
    "network": "gate-testnet",
    "chainId": 10087,
    "eid": 40421,
    "name": "GateLayer Testnet",
    "nativeCurrency": {
      "name": "GATE",
      "symbol": "GATE",
      "decimals": 18
    },
    "rpcUrl": "https://gatelayer-testnet.gatenode.cc",
    "explorerUrl": ""
  },
  "sepolia": {
    "network": "sepolia",
    "chainId": 11155111,
    "eid": 40161,
    "name": "Sepolia",
    "nativeCurrency": {
      "name": "SepoliaETH",
      "symbol": "ETH",
      "decimals": 18
    },
    "rpcUrl": "https://eth-sepolia.g.alchemy.com/v2/rfdRP2gPYwl28VMWGwyA480qNKpB0h2f",
    "explorerUrl": "https://sepolia.etherscan.io"
  }
},
  tokens: {
  "USDT": {
    "key": "USDT",
    "symbol": "USDT",
    "decimals": 6,
    "kind": "OFT_ADAPTER",
    "perChain": {
      "gate-testnet": {
        "token": "0xBdf0A1911f859cCC5DC70976bB0B19e37D4e27f6",
        "adapter": "0x032Dfe105C73f516b07aa95202733a3448e6B8Bc"
      },
      "sepolia": {
        "token": "0x49f107cDD2C0FD3a03b9613633716fB240374a6e",
        "adapter": "0xe0EF48F595349B89F2bBF9185A4f5A7855567338"
      }
    }
  }
}
} as const
